displayName=Rapid Holster
author=RapidUrsa
support=https://github.com/RapidUrsa/RapidHolster
description=Visually holster equipped weapons on your character.
tags=weapon,holster,sheathe,cosmetic,fashionscape
plugins=com.rapidursa.holster.RapidHolsterPlugin
version=1.0.0
build=standard
