displayName=Rapid Holster
author=RapidUrsa
support=https://github.com/RapidUrsa/RapidHolster
description=Visually holster equipped weapons and off-hand items on your character.
tags=weapon,shield,offhand,holster,sheathe,cosmetic,fashionscape
plugins=com.rapidursa.holster.RapidHolsterPlugin
version=2.0.2
build=standard
